version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: "mongodb://qa-db-url:27017/mydb"
    volumes:
      - .:/app
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"