version: "3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://pereraalc2000:mhTkwZseieVz4TvG@cypto.lcbt1.mongodb.net/?retryWrites=true&w=majority&appName=cypto"
    restart: always
