name: Deploy to AWS

on:
  push:
    branches:
      - prod  # Only trigger deployment on pushes to the prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-west-2

      - name: Build and push Docker image to ECR
        run: |
          docker build -t my-app:$GITHUB_SHA .
          docker tag my-app:$GITHUB_SHA <your-ecr-repo-uri>:latest
          docker push <your-ecr-repo-uri>:latest

      - name: Deploy to Amazon ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service --cluster <your-cluster-name> --service <your-service-name> --force-new-deployment
