name: CI/CD Pipeline for Production

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build Docker image
        run: |
          docker build -t myapp:$GITHUB_SHA .

      - name: Tag and Push Docker image to ECR
        run: |
          docker tag myapp:$GITHUB_SHA 123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
          docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp:latest

  # Test job
  test:
    needs: build  # Test after the build job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover tests  # This runs all tests in the "tests" folder

  deploy:
    needs: test  # Only deploy after successful test execution
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Amazon ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
